# Spring MVC dispatcher servlet path. Needs to be different than Jersey's to enable/disable Actuator endpoints access (/info, /health, ...)
server.servlet-path: /
# Jersey dispatcher servlet
spring.jersey.application-path: /api

#Mongo DB config
spring:
  data:
    mongodb:
      database: myspringjersey
      host: localhost
      port: 27017
